name: Java CI
on:
  push:
    branches:
      - main
      - integration
  pull_request:
    branches:
      - main
      - integration
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Java
        run: java -version

      - name: Check Maven
        run: mvn -version

      - name: Build and Test
        run: mvn clean verify

      - name: Check Sonar token
        shell: powershell
        run: |
          if ([string]::IsNullOrEmpty("${{ secrets.SONAR_TOKEN }}")) {
            Write-Host "SONAR_TOKEN is NOT available"
            exit 1
          } else {
            Write-Host "SONAR_TOKEN is available"
          }

      - name: SonarQube analysis
        shell: powershell
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar "-Dsonar.qualitygate.wait=true"

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/