name: Java CI
on:
  push:
    branches:
      - main
      - integration
  pull_request:
    branches:
      - main
      - integration
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Java
        run: java -version

      - name: Check Maven
        run: mvn -version

      - name: Build and Test
        run: mvn clean verify

      - name: SonarQube analysis
        run:  mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }} -Dsonar.host.url=http://localhost:9000 -Dsonar.token=${{ secrets.SONAR_TOKEN }}
